#
#  This file is part of the Meeds project (https://meeds.io/).
#
#  Copyright (C) 2026 Meeds Association contact@meeds.io
#  This program is free software; you can redistribute it and/or
#  modify it under the terms of the GNU Lesser General Public
#  License as published by the Free Software Foundation; either
#  version 3 of the License, or (at your option) any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
#  Lesser General Public License for more details.
#
#  You should have received a copy of the GNU Lesser General Public License
#  along with this program; if not, write to the Free Software Foundation,
#  Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#
spring.liquibase.change-log=classpath:changelog/authserver-rdbms.db.changelog.xml

spring.mvc.servlet.path=/

# Oauth Issuer Base URL
meeds.oauth.issuer-url=${exo.base.url:http://127.0.0.1:8080}/auth-server

# Oauth Public Clients Default Settings
meeds.oauth.public-client.token.authorization-code-time-to-live=${meeds.oauth.client.token.authorization-code.expiration:PT15M}
meeds.oauth.public-client.token.access-token-time-to-live=${meeds.oauth.client.token.access.expiration:PT1H}
meeds.oauth.public-client.token.refresh-token-time-to-live=${meeds.oauth.client.token.refresh.expiration:P30D}
meeds.oauth.public-client.token.access-token-format=${meeds.oauth.client.token.access-token-format:reference}
meeds.oauth.public-client.token.reuse-refresh-tokens=${meeds.oauth.client.token.reuse-refresh-tokens:false}
meeds.oauth.public-client.require-proof-key=true
meeds.oauth.public-client.require-authorization-consent=true
